CONST_SPRITE_NUMBER_PACMAN          = 0
CONST_SPRITE_NUMBER_RED_GHOST       = 1
CONST_SPRITE_NUMBER_PINK_GHOST      = 2
CONST_SPRITE_NUMBER_BLUE_GHOST      = 3
CONST_SPRITE_NUMBER_ORANGE_GHOST    = 4
CONST_SPRITE_NUMBER_POWER_DOT_1     = 5
CONST_SPRITE_NUMBER_POWER_DOT_2     = 6
CONST_SPRITE_NUMBER_POWER_DOT_3     = 7
CONST_SPRITE_NUMBER_POWER_DOT_4     = 8
CONST_SPRITE_NUMBER_FRUIT           = 9
CONST_SPRITE_BOARD_1                 = 10
CONST_SPRITE_BOARD_2                 = 11
CONST_SPRITE_BOARD_3                 = 12
CONST_SPRITE_BOARD_4                 = 13
CONST_SPRITE_BOARD_5                 = 14
CONST_SPRITE_BOARD_6                 = 15
CONST_SPRITE_BOARD_7                 = 16
CONST_SPRITE_BOARD_8                 = 17
CONST_SPRITE_NUMBER_LIFE_1           = 18
CONST_SPRITE_NUMBER_LIFE_2           = 19
CONST_SPRITE_NUMBER_LIFE_3           = 20
CONST_SPRITE_NUMBER_LIFE_4           = 21
CONST_SPRITE_NUMBER_LIFE_5           = 22
CONST_SPRITE_NUMBER_MENU_PLAYER      = 23
CONST_SPRITE_NUMBER_MENU_GHOST       = 24

CONST_SPRITE_PD_1_X = 4
CONST_SPRITE_PD_1_Y = 1

CONST_SPRITE_PD_2_X = 35
CONST_SPRITE_PD_2_Y = 1

CONST_SPRITE_PD_3_X = 4
CONST_SPRITE_PD_3_Y = 21

CONST_SPRITE_PD_4_X = 35
CONST_SPRITE_PD_4_Y = 21

CONST_SPRITE_START      = sprite_0
CONST_SPRITE_SIZE       = 16 * 16
CONST_PC_SPRITE_RIGHT   = sprite_0 + CONST_SPRITE_SIZE * 1
CONST_PC_SPRITE_LEFT    = sprite_0 + CONST_SPRITE_SIZE * 13
CONST_PC_SPRITE_UP      = sprite_0 + CONST_SPRITE_SIZE * 15
CONST_PC_SPRITE_DOWN    = sprite_0 + CONST_SPRITE_SIZE * 17
CONST_PC_SPRITE_COSED   = sprite_0 + CONST_SPRITE_SIZE * 2

CONST_RG_SPRITE_RIGHT_1 = sprite_0 + CONST_SPRITE_SIZE * 24
CONST_RG_SPRITE_RIGHT_2 = sprite_0 + CONST_SPRITE_SIZE * 25
CONST_RG_SPRITE_LEFT_1  = sprite_0 + CONST_SPRITE_SIZE * 26
CONST_RG_SPRITE_LEFT_2  = sprite_0 + CONST_SPRITE_SIZE * 27
CONST_RG_SPRITE_UP_1    = sprite_0 + CONST_SPRITE_SIZE * 28
CONST_RG_SPRITE_UP_2    = sprite_0 + CONST_SPRITE_SIZE * 29
CONST_RG_SPRITE_DOWN_1  = sprite_0 + CONST_SPRITE_SIZE * 30
CONST_RG_SPRITE_DOWN_2  = sprite_0 + CONST_SPRITE_SIZE * 31

CONST_FR_SPRITE_BLUE_1  = sprite_0 + CONST_SPRITE_SIZE * 32
CONST_FR_SPRITE_BLUE_2  = sprite_0 + CONST_SPRITE_SIZE * 33
CONST_FR_SPRITE_WHITE_1 = sprite_0 + CONST_SPRITE_SIZE * 34
CONST_FR_SPRITE_WHITE_2 = sprite_0 + CONST_SPRITE_SIZE * 35

CONST_PG_SPRITE_RIGHT_1 = sprite_0 + CONST_SPRITE_SIZE * 36
CONST_PG_SPRITE_RIGHT_2 = sprite_0 + CONST_SPRITE_SIZE * 37
CONST_PG_SPRITE_LEFT_1  = sprite_0 + CONST_SPRITE_SIZE * 38
CONST_PG_SPRITE_LEFT_2  = sprite_0 + CONST_SPRITE_SIZE * 39
CONST_PG_SPRITE_UP_1    = sprite_0 + CONST_SPRITE_SIZE * 40
CONST_PG_SPRITE_UP_2    = sprite_0 + CONST_SPRITE_SIZE * 41
CONST_PG_SPRITE_DOWN_1  = sprite_0 + CONST_SPRITE_SIZE * 42
CONST_PG_SPRITE_DOWN_2  = sprite_0 + CONST_SPRITE_SIZE * 43

CONST_EYE_SPRITE_RIGHT  = sprite_0 + CONST_SPRITE_SIZE * 44
CONST_EYE_SPRITE_LEFT   = sprite_0 + CONST_SPRITE_SIZE * 45
CONST_EYE_SPRITE_UP     = sprite_0 + CONST_SPRITE_SIZE * 46
CONST_EYE_SPRITE_DOWN   = sprite_0 + CONST_SPRITE_SIZE * 47

CONST_BG_SPRITE_RIGHT_1 = sprite_0 + CONST_SPRITE_SIZE * 48
CONST_BG_SPRITE_RIGHT_2 = sprite_0 + CONST_SPRITE_SIZE * 49
CONST_BG_SPRITE_LEFT_1  = sprite_0 + CONST_SPRITE_SIZE * 50
CONST_BG_SPRITE_LEFT_2  = sprite_0 + CONST_SPRITE_SIZE * 51
CONST_BG_SPRITE_UP_1    = sprite_0 + CONST_SPRITE_SIZE * 52
CONST_BG_SPRITE_UP_2    = sprite_0 + CONST_SPRITE_SIZE * 53
CONST_BG_SPRITE_DOWN_1  = sprite_0 + CONST_SPRITE_SIZE * 54
CONST_BG_SPRITE_DOWN_2  = sprite_0 + CONST_SPRITE_SIZE * 55

CONST_OG_SPRITE_RIGHT_1 = sprite_0 + CONST_SPRITE_SIZE * 60
CONST_OG_SPRITE_RIGHT_2 = sprite_0 + CONST_SPRITE_SIZE * 61
CONST_OG_SPRITE_LEFT_1  = sprite_0 + CONST_SPRITE_SIZE * 62
CONST_OG_SPRITE_LEFT_2  = sprite_0 + CONST_SPRITE_SIZE * 63
CONST_OG_SPRITE_UP_1    = sprite_0 + CONST_SPRITE_SIZE * 64
CONST_OG_SPRITE_UP_2    = sprite_0 + CONST_SPRITE_SIZE * 65
CONST_OG_SPRITE_DOWN_1  = sprite_0 + CONST_SPRITE_SIZE * 66
CONST_OG_SPRITE_DOWN_2  = sprite_0 + CONST_SPRITE_SIZE * 67

CONST_CHERRY_SPRITE     = sprite_0 + CONST_SPRITE_SIZE * 72
CONST_STRAWBERRY_SPRITE = sprite_0 + CONST_SPRITE_SIZE * 73
CONST_ORANGE_SPRITE     = sprite_0 + CONST_SPRITE_SIZE * 74
CONST_APPLE_SPRITE      = sprite_0 + CONST_SPRITE_SIZE * 75
CONST_MELON_SPRITE      = sprite_0 + CONST_SPRITE_SIZE * 76
CONST_GALAXIAN_SPRITE   = sprite_0 + CONST_SPRITE_SIZE * 77
CONST_BELL_SPRITE       = sprite_0 + CONST_SPRITE_SIZE * 78
CONST_KEY_SPRITE        = sprite_0 + CONST_SPRITE_SIZE * 79

CONST_POWER_DOT_SPRITE  = sprite_0 + CONST_SPRITE_SIZE * 108

CONST_FRUIT_TILE_X = 19
CONST_FRUIT_TILE_Y = 17

CONST_RG_INIT_TILE_X = 20
CONST_RG_INIT_TILE_Y = 11

CONST_GHOST_EXIT_TILE_X = 20
CONST_GHOST_EXIT_TILE_Y = 11

CONST_GHOST_HOME_TILE_X = 20
CONST_GHOST_HOME_TILE_Y = $0d

CONST_PG_INIT_TILE_X = 18
CONST_PG_INIT_TILE_Y = 14

CONST_og_INIT_TILE_X = 16
CONST_og_INIT_TILE_Y = 14

CONST_BG_INIT_TILE_X = 22
CONST_BG_INIT_TILE_Y = 14

CONST_PM_INIT_TILE_X = 19
CONST_PM_INIT_TILE_Y = 21

CONST_DIRECTION_UP      = 0
CONST_DIRECTION_DOWN    = 1
CONST_DIRECTION_LEFT    = 2
CONST_DIRECTION_RIGHT   = 3

CONST_GAME_MODE_CHASE       = 0
CONST_GAME_MODE_SCATTER     = 1
CONST_GAME_MODE_FRIGHTENED  = 2
CONST_GAME_MODE_EATEN       = 3
CONST_GAME_MODE_HOME        = 4
