
.include "constants.asm"
.include "game.asm"
.include "game_mode.asm"
.include "plot_ghost.asm"
.include "tile_api.asm"
.include "splash.asm"
.include "state_machine.asm"
.include "menu.asm"
.include "collission.asm"
.include "fruit.asm"
.include "ghost_score.asm"
.include "score_fruit.asm"
.include "game_speed.asm"
.include "game_over.asm"
.include "hi_score.asm"
.include "reset.asm"